// Generated by CoffeeScript 1.8.0
(function() {
  if (typeof console === "undefined" || console === null) {
    window.console = {
      log: function() {},
      debug: function() {},
      info: function() {},
      warn: function() {},
      error: function() {}
    };
  }

  ["log", "warn"].forEach(function(method) {
    var old;
    old = console[method];
    return console[method] = function() {
      var args, e, stack;
      try {
        stack = (new Error()).stack.split(/\n/);
        if (stack[0].indexOf("Error") === 0) {
          stack = stack.slice(1);
        }
        args = [].slice.apply(arguments).concat([stack[1].trim()]);
        return old.apply(console, args);
      } catch (_error) {
        e = _error;
      }
    };
  });

  if (!window.location.hash) {
    window.location = "experience/#/winning_the_presidency";
  } else {
    console.log('sdf');
    require.config({
      urlArgs: "v=2016-11-22",
      baseUrl: "/modules/custom/ike_pivitol_moments/src/",
      paths: {
        jquery: "js/libs/jquery",
        animate: "js/libs/jquery.animate",
        underscore: "js/libs/underscore",
        backbone: "js/libs/backbone",
        text: "js/libs/text",
        modernizr: "js/libs/modernizr",
        videojs: "js/libs/video",
        easeljs: "js/libs/easel",
        preloadjs: "js/libs/preload",
        tweenjs: "js/libs/tween",
        soundjs: "js/libs/sound",
        flashaudio: "js/libs/flashaudio.plugin",
        swfobject: "js/libs/swfobject",
        routes: "js/experience/routes",
        tweenlite: "js/libs/tweenlite.min",
        sharerjs: "js/libs/sharer",
        dotdot: "js/libs/jquery.dotdotdot.min"
      },
      shim: {
        jquery: {
          exports: "$"
        },
        animate: {
          exports: "animate",
          deps: ["jquery"]
        },
        underscore: {
          exports: "_"
        },
        backbone: {
          deps: ["underscore", "jquery"],
          exports: "Backbone"
        },
        modernizr: {
          exports: "Modernizr"
        },
        videojs: {
          deps: ["modernizr"],
          exports: "_V_"
        },
        easeljs: {
          exports: "createjs"
        },
        preloadjs: {
          deps: ["easeljs", "soundjs"],
          exports: "createjs"
        },
        soundjs: {
          deps: ["easeljs", "flashaudio"],
          exports: "createjs"
        },
        flashaudio: {
          deps: ["easeljs", "swfobject"],
          exports: "createjs"
        },
        tweenjs: {
          deps: ["easeljs"],
          exports: "createjs"
        },
        swfobject: {
          exports: "swfobject"
        },
        sharerjs: {
          exports: "sharerjs"
        },
        tweenlite: {
          exports: "TweenLite"
        }
      }
    });
    require(["modernizr", "jquery"], function(Modernizr, $) {
      if (Modernizr.canvas) {
        return require(["js/experience/app"], function(App) {
          return App.init();
        });
      } else {
        $(".no-canvas-message").show();
        return $(".main-site").hide();
      }
    });
  }

}).call(this);
