// Generated by CoffeeScript 1.8.0
(function() {
  define({
    data: [
      {
        title: "Pivotal Moments",
        section: "Pivotal Moments",
        url: "",
        js: "js/experience/views/pageThemeSelectorView",
        api: "/api/pm-themes.json"
      }, {
        title: "D-Day",
        section: "D-Day",
        url: "dday",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "Nato",
        section: "Nato",
        url: "nato",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "Little Rock",
        section: "Little Rock",
        url: "little_rock",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "West Point",
        section: "West Point",
        url: "west_point",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "Winning the Presidency",
        section: "Winning the Presidency",
        url: "winning_the_presidency",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "Waging Peace",
        section: "Waging Peace",
        url: "waging_peace",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }, {
        title: "Space Race",
        section: "Space Race",
        url: "space_race",
        js: "js/experience/views/pageThemeView",
        api: {
          "intro": "/api/pm-intro.json",
          "contents": "/api/pm-subthemes.json",
          "slideshow": "/api/pm-subtheme-slideshow",
          "panorama": "/api/panorama.json",
          "about": "/about_experience"
        }
      }
    ]
  });

}).call(this);
