// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone", "js/experience/models/slideModel"], function(_, Backbone, SlideModel) {
    return Backbone.Collection.extend({
      model: SlideModel
    });
  });

}).call(this);
