// Generated by CoffeeScript 1.8.0

/*
ABOUT VIEW COMPONENT
Args: data: text to add to content
 */

(function() {
  define(["jquery", "underscore", "backbone", "text!partials/experience/_about.html"], function($, _, Backbone, HTML) {
    return Backbone.View.extend({
      className: "about-view",
      events: {
        "click .close-button, .background": "close"
      },
      isReady: function() {
        return this._ready || false;
      },
      open: function() {
        if (this._isOpen) {
          return;
        }
        this._isOpen = true;
        return this.$el.fadeIn();
      },
      close: function() {
        if (!this._isOpen) {
          return;
        }
        this._isOpen = false;
        return this.$el.fadeOut();
      },
      setData: function(data) {
        return this.$(".about-content").html(data);
      },
      initialize: function(args) {
        this.$el.html(HTML);
        if (!this.$el.hasClass(this.className)) {
          this.$el.addClass(this.className);
        }
        return this._ready = true;
      },
      destroy: function() {
        this._isOpen = null;
        return this.remove();
      }
    });
  });

}).call(this);
