// Generated by CoffeeScript 1.8.0

/*
INTRO THEME VIEW
General view to introduce theme on the theme selector view
 */

(function() {
  define(["underscore", "backbone", "text!partials/experience/_introThemeView.tpl.html"], function(_, Backbone, templateHTML) {
    return Backbone.View.extend({
      className: "intro-theme-view",
      events: {
        "submit form": "_onFormSubmit"
      },
      initialize: function() {
        var o;
        o = this.model.toJSON();
        o["formid"] = window.gn_formid;
        this.$el.html(_.template(templateHTML, o)).css("background-image", "url(\"" + o["image_url"] + "\")");
        this.$loader = this.$(".loader");
        return this.$button = this.$(".button");
      },
      setLoadProgress: function(loaded) {
        if (loaded == null) {
          loaded = -1;
        }
        if (loaded >= 0) {
          this.$button.hide();
          return this.$loader.text(parseInt(loaded * 100) + "% loaded");
        } else {
          this.$button.show();
          return this.$loader.text("");
        }
      },
      _onFormSubmit: function(event) {
        var $form;
        event.preventDefault();
        $form = this.$("form");
        return $.ajax({
          url: "/services/session/token",
          type: "get",
          error: (function(_this) {
            return function(response) {
              return _this._onFormError(response);
            };
          })(this),
          success: (function(_this) {
            return function(response) {
              return $.ajax({
                url: $form.attr("action"),
                type: $form.attr("method"),
                data: $form.serialize(),
                beforeSend: function(request) {
                  return request.setRequestHeader("X-CSRF-Token", response);
                },
                error: function(response) {
                  return _this._onFormError(response);
                },
                success: function(response) {
                  return $form.parent().html("Thanks. You will be notified when this pivotal moment launches.");
                }
              });
            };
          })(this)
        });
      },
      _onFormError: function(response) {
        return this.$("form").parent().html("There's an error with your submission. Please try again later.");
      }
    });
  });

}).call(this);
