// Generated by CoffeeScript 1.8.0

/*
PAGE THEME SELECTOR VIEW
Main navigation view to select pivotal moment theme
 */

(function() {
  define(["underscore", "jquery", "backbone", "js/components/views/sliderView", "js/experience/models/introModel", "js/experience/views/introThemeView"], function(_, $, Backbone, SliderView, IntroModel, IntroThemeView) {
    return Backbone.View.extend({
      className: "page-theme-selector",
      events: {
        "click .sections-nav": "_onThemeControlClick"
      },
      initialize: function() {
        this.slider = new SliderView({
          el: this.$(".slider-component")[0],
          width: "100%",
          height: "100%",
          viewClass: IntroThemeView,
          collection: new Backbone.Collection()
        });
        this.slider.$el.hide();
        this._$left = this.$(".sections-nav.left");
        this._$right = this.$(".sections-nav.right");
        this.slider.collection.model = IntroModel;
        this.slider.collection.url = this.model.get("api");
        this.slider.collection.comparator = "year";
        this.slider.collection.on("reset", this._onSliderCollectionReset, this);
        return this.slider.collection.fetch({
          reset: true
        });
      },
      updateURL: function(path, duration) {
        var index, model, url;
        if (duration == null) {
          duration = 1000;
        }
        this.path = path;
        if (!this.slider.collection.length) {
          return;
        }
        url = window.location.href.split("#");
        _u = url[0]
        if (_u.length > 0 && _u[_u.length - 1] !== '/') {
          _u = url[0] + "/#/" + path;
        } else {
          _u = url[0] + "#/" + path;
        }
        model = this.slider.collection.findWhere({
          target_url: _u
        });
        if (model === undefined) {
          console.log("Could not find the model");
        }
        index = this.slider.collection.indexOf(model);
        if (index >= 0 && index !== this.slider.getIndex()) {
          this.slider.moveTo(index, duration);
        }
        if (index === 0) {
          this._$left.fadeOut();
        } else {
          this._$left.fadeIn();
        }
        if (index === this.slider.collection.length - 1) {
          return this._$right.fadeOut();
        } else {
          return this._$right.fadeIn();
        }
      },
      setLoadProgress: function(loaded) {
        var view;
        if (loaded == null) {
          loaded = -1;
        }
        view = this.slider.getView(this.slider.getIndex());
        return view.setLoadProgress(loaded);
      },
      _onThemeControlClick: function(event) {
        var index, model;
        index = this.$(event.currentTarget).hasClass("left") ? this.slider.index - 1 : this.slider.index + 1;
        if (index < 0 || index >= this.slider.collection.length) {
          return;
        }
        model = this.slider.collection.at(index);
        return window.location.href = model.get("target_url");
      },
      _onSliderCollectionReset: function(collection) {
        this.slider.$el.fadeIn();
        return this.updateURL(this.path, 0);
      }
    });
  });

}).call(this);
