// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Collection.extend({
      exclude: function(list, attrName) {
        this.exclusions = list;
        return this.excludeAttr = attrName;
      },
      parse: function(response) {
        var self;
        if (this.exclusions && this.excludeAttr) {
          self = this;
          response = _.reject(response, function(o) {
            if (_.indexOf(self.exclusions, o[self.excludeAttr]) > -1) {
              return true;
            } else {
              return false;
            }
          });
        }
        return response;
      }
    });
  });

}).call(this);
