// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "js/memorial/views/generalSectionView", "text!partials/memorial/_featuredsection.tpl.html", "text!partials/memorial/_ikesection.tpl.html"], function(_, GeneralSectionView, template, altTemplate) {
    return GeneralSectionView.extend({
      initialize: function(args) {
        this.template = (!this.model.get("target_url") ? template : altTemplate);
        return this.render();
      },
      render: function() {
        if (this.template && this.model) {
          this.$el.html(_.template(this.template, this.model.toJSON()));
        }
        return this;
      }
    });
  });

}).call(this);
