// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "js/memorial/views/generalSectionView", "text!partials/memorial/_ikesection.tpl.html"], function(_, GeneralSectionView, template) {
    return GeneralSectionView.extend({
      initialize: function(args) {
        this.template = template;
        return this.render();
      }
    });
  });

}).call(this);
