// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone", "text!partials/memorial/_image.tpl.html"], function(_, Backbone, template) {
    return Backbone.View.extend({
      className: "image-view",
      initialize: function(args) {
        this.template = _.template(template);
        return this.render();
      },
      render: function() {
        this.$el.empty();
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      }
    });
  });

}).call(this);
