// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery", "underscore", "backbone", "text!partials/memorial/_linklist.tpl.html"], function($, _, Backbone, template) {
    return Backbone.View.extend({
      tagName: "ul",
      className: "link-list-view",
      initialize: function(args) {
        this.collection = args.collection;
        this.collection.on("all", this.render, this);
        return this.template = _.template(template);
      },
      render: function() {
        var groupList, groups, json, self;
        this.$el.empty();
        json = this.collection.toJSON();
        groupList = [];
        groups = {};
        _.each(json, function(o) {
          var g, tag;
          tag = o["tag"];
          g = groups[tag];
          if (!g) {
            g = {
              tag: tag,
              links: []
            };
            groups[tag] = g;
            groupList.push(g);
          }
          return g["links"].push(o);
        });
        self = this;
        _.each(groupList, function(o) {
          return self.$el.append(self.template(o));
        });
        return this;
      },
      destroy: function() {
        this.collection.off("all", this.render, this);
        return this.remove();
      }
    });
  });

}).call(this);
