// Generated by CoffeeScript 1.8.0

/*
GENERAL LIST VIEW : No interactivity, just define collection and template to have it render and updated
Args:{
collection: collection of models consistent with template
template: template html consistent with models of collection
}
 */

(function() {
  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    return Backbone.View.extend({
      className: "list-view",
      initialize: function(args) {
        this.template = _.template(args.template);
        this.collection = args.collection;
        return this.collection.on("all", this.render, this);
      },
      render: function() {
        var self;
        this.$el.empty();
        self = this;
        this.collection.each(function(model) {
          return self.$el.append(self.template(model.toJSON()));
        });
        return this;
      },
      destroy: function() {
        this.collection.off("all", this.render, this);
        return this.remove();
      }
    });
  });

}).call(this);
