// Generated by CoffeeScript 1.8.0

/*
MEMBER LIST VIEW
Args:{
collection: collection
}
 */

(function() {
  define(["jquery", "underscore", "backbone", "js/memorial/models/memberModel", "text!partials/memorial/_member.tpl.html"], function($, _, Backbone, ModelClass, template) {
    return Backbone.View.extend({
      className: "member-list-view",
      events: {
        "click .switch": "_onSwitchClicked"
      },
      initialize: function(args) {
        this.template = _.template(template);
        this.collection.model = ModelClass;
        this.collection.on("all", this.render, this);
        return this.render();
      },
      render: function() {
        var self;
        this.$el.empty();
        if (!this.collection.length) {
          return;
        }
        self = this;
        this.collection.each(function(model) {
          return self.$el.append(self.template(model.toJSON()));
        });
        this.$(".switch").click();
        return this;
      },
      _onSwitchClicked: function(event) {
        var $target;
        $target = $(event.currentTarget);
        if ($target.hasClass("active")) {
          return $target.removeClass("active").parent().children(".biography").hide();
        } else {
          return $target.addClass("active").parent().children(".biography").show();
        }
      },
      destroy: function() {
        this.collection.off("all", this.render, this);
        return this.remove();
      }
    });
  });

}).call(this);
