// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "js/memorial/views/generalSectionView", "text!partials/memorial/_memorialsection.tpl.html"], function(_, GeneralSectionView, template) {
    return GeneralSectionView.extend({
      initialize: function(args) {
        this.template = template;
        return this.render();
      },
      render: function() {
        if (this.template && this.model) {
          this.$el.html(_.template(this.template, this.model.toJSON()));
        }
        return this;
      }
    });
  });

}).call(this);
