// Generated by CoffeeScript 1.8.0
(function() {
  define(["js/memorial/views/pageMemorialView"], function(ParentClass) {
    return ParentClass.extend({
      className: "page-memorial-view page-memorial-first-view",
      _onComponentIndexChange: function(index) {
        ParentClass.prototype._onComponentIndexChange.call(this, index);
        if (index === 0) {
          this.gallery.$leftControl.hide();
          return this.infoBox.$prevbtn.hide();
        } else {
          this.gallery.$leftControl.show();
          return this.infoBox.$prevbtn.show();
        }
      }
    });
  });

}).call(this);
