// Generated by CoffeeScript 1.8.0

/*
CREDITS VIEW PAGE
Args:{
model : urlModel with page data (assigned before initialize by parent class)
}
Triggers:
"ready" : function(view) when it's ready to be displayed
 */

(function() {
  define(["jquery", "underscore", "backbone", "text!partials/memorial/_credits.html"], function($, _, Backbone, html) {
    return Backbone.View.extend({
      className: "page-credits-view",
      initialize: function() {
        this.$el.html(html);
        return this.trigger("ready", this);
      },
      destroy: function() {
        return this.remove();
      }
    });
  });

}).call(this);
