// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery", "underscore", "backbone", "js/memorial/views/pageMemorialView", "js/memorial/models/videoSectionModel", "js/memorial/views/videoSectionView"], function($, _, Backbone, ParentClass, SectionModel, VideoView) {
    return ParentClass.extend({
      className: "page-memorial-view page-memorial-video-view",
      initialize: function(args) {
        this.sectionModel = SectionModel;
        this.sectionView = VideoView;
        return ParentClass.prototype.initialize.call(this);
      }
    });
  });

}).call(this);
