// Generated by CoffeeScript 1.8.0

/*
MEMBER LIST PAGE VIEW
Args:{
model : urlModel with page data (assigned before initialize by parent class)
}
Triggers:
"ready" : function(view) when it's ready to be displayed
 */

(function() {
  define(["jquery", "underscore", "backbone", "js/memorial/views/memberListView", "text!partials/memorial/_memberlistpage.html"], function($, _, Backbone, ListViewClass, html) {
    return Backbone.View.extend({
      className: "page-member-list-view",
      initialize: function() {
        var collection;
        this.$el.html(html);
        this.$el.children(".title").text(this.model.get("title"));
        collection = new Backbone.Collection();
        collection.url = this.model.get("api");
        collection.on("reset", this.onCollectionReset, this);
        collection.fetch();
        this.listView = new ListViewClass({
          collection: collection
        });
        return this.$el.children(".content").html(this.listView.el);
      },
      onCollectionReset: function(collection) {
        collection.off("reset", this.onCollectionReset, this);
        return this.trigger("ready", this);
      },
      destroy: function() {
        if (this.listView.destroy !== undefined) {
          this.listView.destroy();
        }
        return this.remove();
      }
    });
  });

}).call(this);
