// Generated by CoffeeScript 1.8.0

/*
JOIN US PAGE
Args:{
model : urlModel with page data (assigned before initialize by parent class)
}
Triggers:
"ready" : function(view) when it's ready to be displayed
 */

(function() {
  define(["jquery", "underscore", "backbone", "text!partials/memorial/_joinus.html"], function($, _, Backbone, html) {
    return Backbone.View.extend({
      className: "page-joinus-view",
      initialize: function() {
        return this.$el.html(html);
      },
      onComplete: function() {
        if (this.orgListReady && this.faqListReady) {
          return this.trigger("ready", this);
        }
      },
      destroy: function() {
        return this.remove();
      }
    });
  });

}).call(this);
