// Generated by CoffeeScript 1.8.0
(function() {
  define(["js/memorial/views/pageMemorialView"], function(ParentClass) {
    return ParentClass.extend({
      className: "page-memorial-view page-memorial-last-view",
      _onComponentIndexChange: function(index) {
        ParentClass.prototype._onComponentIndexChange.call(this, index);
        if (index === this.collection.length - 1) {
          this.gallery.$rightControl.hide();
          return this.infoBox.$nextbtn.hide();
        } else {
          this.gallery.$rightControl.show();
          return this.infoBox.$nextbtn.show();
        }
      }
    });
  });

}).call(this);
