// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery", "underscore", "backbone", "sharerjs", "text!partials/memorial/_sharingbox.html"], function($, _, Backbone, sharerjs, html) {
    return Backbone.View.extend({
      className: "sharing-box-view",
      MAX_CHARS: 300,
      EMAIL_URL: "/content/share-page",
      getContents: function() {
        return this._contents;
      },
      setContents: function(contents) {
        contents = contents || {};
        contents["url"] = contents["url"] || window.location;
        contents["caption"] = contents["title"] || "";
        contents["title"] = $("meta[property=\"og:title\"]").attr("content") || "";
        contents["image"] = contents["image"] || $("meta[property=\"og:image\"]").attr("content") || "";
        contents["description"] = contents["description"] || $("meta[property=\"og:description\"]").attr("content") || "";
        if (contents["description"].length > this.MAX_CHARS) {
          contents["description"] = contents["description"].substr(0, this.MAX_CHARS) + "...";
        }
        return this._contents = contents;
      },
      initialize: function(args) {
        args = args || {};
        this.$el.html(html);
        this.$box = this.$el.children(".sharing-list").hide();
        this.$el.on("mouseover", (function(_this) {
          return function() {
            return _this.$box.show();
          };
        })(this));
        this.$el.on("mouseleave", (function(_this) {
          return function() {
            return _this.$box.hide();
          };
        })(this));
        this.setContents(args.contents);
        this.$el.find(".link.facebook").click((function(_this) {
          return function(event) {
            return sharerjs.getFacebookSharer(_this.getContents(), {
              appId: "286058441531272"
            }).call();
          };
        })(this));
        this.$el.find(".link.twitter").click((function(_this) {
          return function(event) {
            return sharerjs.getTwitterSharer(_this.getContents()).call();
          };
        })(this));
        this.$el.find(".link.youtube").click((function(_this) {
          return function(event) {
            return sharerjs.getYoutube(_this.getContents()).call();
          };
        })(this));
        return this.$el.find(".link.email").click((function(_this) {
          return function(event) {
            var c, url;
            c = _this.getContents();
            url = _this.EMAIL_URL + "?nid=" + c.nid + "&url=" + encodeURIComponent(c.url);
            return sharerjs.getSharer({
              url: url
            }).call();
          };
        })(this));
      },
      destroy: function() {
        this.$el.off("mouseover").off("mouseleave").find("a").off("click");
        return this.remove();
      }
    });
  });

}).call(this);
