// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.View.extend({
      className: "thumbnail-grid-view",
      initialize: function(args) {
        return this.render();
      },
      render: function() {
        this.$el.empty();
        this.$el.html(_.template(template, this.model.toJSON()));
        if (!this.sharingBoxView) {
          this.sharingBoxView = new SharingBoxView();
        }
        this.$el.append(this.sharingBoxView.el);
        return this;
      },
      destroy: function() {}
    });
  });

}).call(this);
