// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone", "js/memorial/models/sectionModel"], function(_, Backbone, ParentModelClass) {
    return ParentModelClass.extend({
      defaults: _.extend({}, ParentModelClass.defaults, {
        section: "",
        url: ""
      })
    });
  });

}).call(this);
