// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        title: "",
        subtitle: "",
        description: "",
        image_url: "",
        image_caption: "",
        image_credit: "",
        target_url: "",
        _total_rows: ""
      },
      getImage: function() {
        return this.attributes["image_url"];
      },
      parse: function(o) {
        var caption;
        caption = o["image_credit"] || o["image_caption"];
        o["image_credit"] = o["image_credit"] || caption;
        o["image_caption"] = o["image_caption"] || caption;
        return o;
      }
    });
  });

}).call(this);
