// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        fullname: "",
        jobtitle: "",
        summary: "",
        biography: "",
        image_url: "",
        image_url_h: "",
        nid: ""
      },
      parse: function(o) {
        o["image_url_h"] = o["image_url_h"] || o["image_url"];
        return o;
      }
    });
  });

}).call(this);
