// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        image_url: "",
        image_caption: "",
        image_credit: "",
        mission: "",
        legislation: "",
        law_url: "",
        law_name: ""
      },
      parse: function(o) {
        return o[0];
      }
    });
  });

}).call(this);
