// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        total: 0,
        offset: 0,
        limit: 5
      }
    });
  });

}).call(this);
