// Generated by CoffeeScript 1.8.0

/*
PDF LINK MODEL
Subclass of link model. It parses the values obtained by a standard pdf call (title, description, pdf, date) into the values expected by link model (name, url, tag)
 */

(function() {
  define(["underscore", "backbone", "js/memorial/models/linkModel"], function(_, Backbone, LinkModelClass) {
    return LinkModelClass.extend({
      parse: function(o) {
        return {
          name: o["title"],
          url: o["pdf"],
          tag: (o["date"] ? o["date"].substring(0, 4) : "-")
        };
      }
    });
  });

}).call(this);
