// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        _total_rows: 0,
        nid: "",
        date: "",
        title: "",
        image_url: "",
        image_caption: "",
        pdf: "",
        featured: false
      },
      parse: function(o) {
        if (o["featured"] !== undefined) {
          o["featured"] = (o["featured"] === "false" ? false : true);
        }
        return o;
      }
    });
  });

}).call(this);
