// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        title: "",
        description: "",
        image_url: "",
        image_url_l: "",
        image_url_m: "",
        image_url_s: "",
        image_credit: "",
        map_url: "",
        map_x: 0,
        map_y: 0,
        order: "",
        _total_rows: ""
      },
      getImage: function(size) {
        switch (size) {
          case "small":
            return this.attributes["image_url_s"];
          case "medium":
            return this.attributes["image_url_m"];
          case "large":
            return this.attributes["image_url_l"];
          default:
            return this.attributes["image_url"];
        }
      },
      parse: function(o) {
        o["image_url"] = o["image_url"] || o["image_url_l"] || o["image_url_m"] || o["image_url_s"];
        o["image_url_l"] = o["image_url_l"] || o["image_url"] || o["image_url_m"] || o["image_url_s"];
        o["image_url_m"] = o["image_url_m"] || o["image_url_l"] || o["image_url"] || o["image_url_s"];
        o["image_url_s"] = o["image_url_s"] || o["image_url_m"] || o["image_url_l"] || o["image_url"];
        return o;
      }
    });
  });

}).call(this);
