// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      defaults: {
        title: "",
        section: "",
        url: "",
        js: "",
        api: "",
        params: ""
      }
    });
  });

}).call(this);
