// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone", "js/memorial/models/sectionModel"], function(_, Backbone, ParentModelClass) {
    return ParentModelClass.extend({
      defaults: _.extend({}, ParentModelClass.defaults, {
        video_url: "",
        video_poster_url: "",
        video_type: "video/mp4"
      }),
      getImage: function() {
        return this.attributes["video_poster_url"];
      }
    });
  });

}).call(this);
