// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      idAttribute: "nid",
      defaults: {
        year: "",
        title: "",
        subtitle: "",
        description: "",
        image_url: "",
        enabled: false
      }
    });
  });

}).call(this);
