// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      IMAGE_TYPE: "image",
      VIDEO_TYPE: "video",
      SPRITESHEET_TYPE: "spritesheet",
      defaults: {
        url: "",
        data: "",
        alpha: 1,
        x: 0,
        y: 0,
        w: null,
        h: null,
        z: 0
      },
      getType: function() {
        if (this._type == null) {
          this._type = (function() {
            switch (false) {
              case !this.get("url").search(/^.*\.(?:jpg|jpeg|png|gif)$/i > -1):
                return this.IMAGE_TYPE;
              case !this.get("url").search(/^.*\.(?:mp4|m4v|ogg|webm)$/i > -1):
                return this.VIDEO_TYPE;
              case !this.get("url").search(/^.*\.(?:json)$/i > -1):
                return this.SPRITESHEET_TYPE;
            }
          }).call(this);
        }
        return this._type;
      }
    });
  });

}).call(this);
