// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone", "js/experience/models/panoramaItemModel"], function(_, Backbone, ItemModel) {
    return Backbone.Model.extend({
      childrenCollection: null,
      defaults: {
        width: 0,
        height: 0,
        audio: "",
        children: null
      },
      initialize: function(args) {
        this.childrenCollection = new Backbone.Collection(this.get("children"), {
          model: ItemModel,
          comparator: "z"
        });
        return this.on("change:children", this.updateChildrenCollection);
      },
      updateChildrenCollection: function() {
        return this.childrenCollection.reset(this.get("children"));
      }
    });
  });

}).call(this);
