// Generated by CoffeeScript 1.8.0
(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      idAttribute: "nid",
      defaults: {
        title: "",
        thumbnail: "",
        description: "",
        image: "",
        index: -1,
        nid: -1,
        alt: "",
        video: [],
        captions: "",
        resources: "",
        zoom_image: [],
        zoom_image_thumb: []
      },
      isPhoto: function() {
        return (this.get("image") !== "");
      }
    });
  });

}).call(this);
