// Generated by CoffeeScript 1.8.0

// /Users/websterjorgensen/Dev/ikemain/ike-drupal-ds4/web/modules/custom/ike_pivitol_moments/src/js/experience/models/subthemeModel.js

(function() {
  define(["underscore", "backbone"], function(_, Backbone) {
    return Backbone.Model.extend({
      idAttribute: "nid",
      defaults: {
        title: "",
        thumbnail: "",
        description: "",
        image: "",
        slides: [],
        index: -1,
        x: 0,
        y: 0
      }
    });
  });

}).call(this);
