// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    urlArgs: "v=4b421f5d0",
    baseUrl: "/static/",
    paths: {
      jquery: "js/libs/jquery",
      underscore: "js/libs/underscore",
      backbone: "js/libs/backbone.0.9.2",
      video: "js/libs/video",
      text: "js/libs/text",
      routes: "js/memorial/routes",
      sharerjs: "js/libs/sharer"
    },
    shim: {
      jquery: {
        exports: "$"
      },
      underscore: {
        exports: "_"
      },
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      video: {
        exports: "_V_"
      },
      sharerjs: {
        exports: "sharerjs"
      }
    }
  });

  require(["js/memorial/app"], function(App) {
    return App.init();
  });

}).call(this);
