// Generated by CoffeeScript 1.8.0
(function() {
  (function() {
    return define({
      data: [
        {
          title: "Overview",
          section: "Overview",
          url: "home",
          js: "js/memorial/views/pageOverviewView",
          api: "/api/sections.json"
        }, {
          title: "Memorial Design",
          section: "Memorial Design",
          url: "memorial/design",
          js: "js/memorial/views/pageMemorialFirstView",
          api: "/api/memorial_design.json"
        }, {
          title: "Memorial Site",
          section: "Memorial Site",
          url: "memorial/site",
          js: "js/memorial/views/pageMemorialView",
          api: "/api/memorial_site.json"
        }, {
          title: "Frank Gehry",
          section: "Frank Gehry",
          url: "memorial/gehry",
          js: "js/memorial/views/pageMemorialVideoView",
          api: "/api/frank_gehry.json"
        }, {
          title: "Tapestry",
          section: "Tapestry",
          url: "memorial/tapestry",
          js: "js/memorial/views/pageMemorialVideoView",
          api: "/api/tapestry.json"
        }, {
          title: "Sculpture",
          section: "Sculpture",
          url: "memorial/sculpture",
          js: "js/memorial/views/pageMemorialVideoView",
          api: "/api/sculpture.json"
        }, {
          title: "Mobile App",
          section: "Mobile App",
          url: "ememorial/app",
          js: "js/memorial/views/pageMemorialLastView",
          api: "/api/ememorial.json"
        }, {
          title: "Pivotal Moments",
          section: "Pivotal Moments",
          url: "experience/",
          js: "js/memorial/views/pageEisenhowerView",
          api: "/api/pm-themes.json"
        }, {
          title: "Mission",
          section: "Mission",
          url: "commission/mission",
          js: "js/memorial/views/pageMissionView",
          api: {
            mission: "/api/commission_mission.json",
            minutes: "/api/meeting_minutes.json",
            budget: "/api/commission_budget.json"
          }
        }, {
          title: "Commissioners",
          section: "Commissioners",
          url: "commission/commissioners",
          js: "js/memorial/views/pageMemberListView",
          api: "/api/commissioners.json"
        }, {
          title: "Legacy Committee",
          section: "Legacy Committee",
          url: "commission/committees",
          js: "js/memorial/views/pageCommitteesView",
          api: {
            legacy: "/api/committee_members.json?committee=Legacy&limit=0",
            advisory: "/api/committee_members.json?committee=Advisory&limit=0",
            international: "/api/committee_members.json?committee=International&limit=0"
          }
        }, {
          title: "Executive Staff",
          section: "Executive Staff",
          url: "commission/staff",
          js: "js/memorial/views/pageMemberListView",
          api: "/api/executive_staff.json"
        }, {
          title: "Current News",
          section: "News",
          url: "news",
          js: "js/memorial/views/pageNewsView",
          api: {
            news: "/api/news.json",
            press: "/api/press.json"
          }
        }, {
          title: "Donate",
          section: "Donate",
          url: "donate",
          js: "js/memorial/views/pageDonateView",
          api: {
            levels: "/api/donation_levels",
            donors: "/api/donors-by-level"
          }
        }, {
          title: "Donate",
          section: "Donate",
          url: "",
          js: "js/memorial/views/pageDonateView",
          api: {
            levels: "/api/donation_levels",
            donors: "/api/donors-by-level"
          }
        }, {
          title: "About the Eisenhower Memorial",
          section: "About",
          url: "about",
          js: "js/memorial/views/pageAboutView",
          api: {
            faq: "/api/faq.json",
            legacy: "/api/organizations.json"
          }
        }, {
          title: "Credits",
          section: "Credits",
          url: "credits",
          js: "js/memorial/views/pageCreditsView",
          api: ""
        }
      ]
    });
  }).call(this);

}).call(this);
