// Generated by CoffeeScript 1.8.0

/*
INDEPENDENT PIECES OF SCRIPT FOR PAGES THAT NEED TO BE OUT OF THE REQUIRE - BACKBONE LOOP
 */

(function() {
  jQuery(document).ready(function($) {
    return $("#site-header .main-menu .menu-item").bind("mouseover", function(event) {
      return $(event.currentTarget).find(".sec-menu").addClass("hover");
    }).bind("mouseleave", function(event) {
      return $(event.currentTarget).find(".sec-menu").removeClass("hover");
    });
  });

}).call(this);
